---
branches:
  only:
  - master

services: docker

language: python
python: "2.7"

env:
  - distro: centos6
    init: /sbin/init
    run_opts: "--privileged"
  - distro: ubuntu1404
    init: /sbin/init
    run_opts: ""

before_install:
  # Pull container.
  - 'docker pull grycap/travis:${distro}'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} grycap/travis:${distro} "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test_server.yml --syntax-check'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test_client.yml --syntax-check'

  # Test role installation.
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test_server.yml'
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test_client.yml'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
